pipeline_name: demo_math_linear_v1
pipeline_tags: [demo, math, linear, basics]
jobs:
  - job_name: job1_square
    ui_name: Job 1 (Square)
    path: runtime_seed/jobs/job1_square/latest/main.py
    deps: []
    outputs: [result]
    inputs:
      number: initial

  - job_name: job2_mirror_add
    ui_name: Job 2 (Mirror Add)
    path: runtime_seed/jobs/job2_mirror_add/latest/main.py
    deps: [job1_square]
    outputs: [result]
    inputs:
      number:
        job: job1_square
        key: result
