#!/usr/bin/env python3
"""Create runtime pipeline groups and optionally seed the demo project."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

DEFAULT_CONFIG = """\
# Generated by install.sh / reload-projects.sh
dagychu_config_version: 1
stack:
  python: "3.12"
  bash: false
dependencies:
  python: []
"""

DEFAULT_GROUPS = ("demo", "development", "production")
# Kept under examples/pipelines for docs, but not installed into the demo project.
DEMO_PIPELINE_EXCLUDE = frozenset({"demo_notify_channel_modes.yaml"})


def parse_pipeline_dirs(raw: str) -> list[tuple[str, str]]:
    if not raw.strip():
        return [(name, name) for name in DEFAULT_GROUPS]
    out: list[tuple[str, str]] = []
    for entry in raw.split(","):
        entry = entry.strip()
        if not entry:
            continue
        if "=" in entry:
            name, root = entry.split("=", 1)
        else:
            name, root = entry, entry
        name = name.strip()
        root = root.strip() or "."
        out.append((name, root))
    return out


def write_config_if_missing(group_root: Path) -> None:
    cfg = group_root / "dagychu-config.yaml"
    if not cfg.is_file():
        cfg.write_text(DEFAULT_CONFIG, encoding="utf-8")


def rewrite_demo_yaml(text: str) -> str:
    return text.replace("runtime_seed/jobs/", "jobs/")


def _copy_tree_no_overwrite(src: Path, dest: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    for item in src.iterdir():
        target = dest / item.name
        if item.is_dir():
            _copy_tree_no_overwrite(item, target)
        elif not target.exists():
            shutil.copy2(item, target)


def seed_demo(pack_root: Path, demo_root: Path) -> None:
    jobs_src = pack_root / "examples" / "runtime_seed" / "jobs"
    if not jobs_src.is_dir():
        jobs_src = pack_root / "examples" / "jobs"
    if jobs_src.is_dir():
        _copy_tree_no_overwrite(jobs_src, demo_root / "jobs")

    pipelines_dest = demo_root / "pipelines"
    pipelines_dest.mkdir(parents=True, exist_ok=True)

    seed_pipelines = pack_root / "examples" / "runtime_seed" / "pipelines"
    if seed_pipelines.is_dir():
        for yaml_path in seed_pipelines.glob("*.yaml"):
            dest = pipelines_dest / yaml_path.name
            if not dest.exists():
                dest.write_text(rewrite_demo_yaml(yaml_path.read_text(encoding="utf-8")), encoding="utf-8")

    examples_pipelines = pack_root / "examples" / "pipelines"
    if examples_pipelines.is_dir():
        for yaml_path in examples_pipelines.glob("*.yaml"):
            if yaml_path.name in DEMO_PIPELINE_EXCLUDE:
                continue
            dest = pipelines_dest / yaml_path.name
            if not dest.exists():
                dest.write_text(rewrite_demo_yaml(yaml_path.read_text(encoding="utf-8")), encoding="utf-8")


def bootstrap_runtime(
    pack_root: Path,
    runtime_host: Path,
    pipeline_dirs: str,
    *,
    seed_demo_project: bool = False,
) -> list[Path]:
    runtime_host.mkdir(parents=True, exist_ok=True)
    created: list[Path] = []
    for _name, group_root in parse_pipeline_dirs(pipeline_dirs):
        if group_root.startswith("repo:"):
            continue
        if group_root in {".", ""}:
            target = runtime_host
        else:
            target = runtime_host / group_root
        target.mkdir(parents=True, exist_ok=True)
        (target / "pipelines").mkdir(exist_ok=True)
        (target / "jobs").mkdir(exist_ok=True)
        write_config_if_missing(target)
        created.append(target)
        if seed_demo_project and group_root.rstrip("/") == "demo":
            seed_demo(pack_root, target)
    # Always ensure the three default projects exist on first install.
    if seed_demo_project:
        for name in DEFAULT_GROUPS:
            target = runtime_host / name
            if not any(p == target for p in created):
                target.mkdir(parents=True, exist_ok=True)
                (target / "pipelines").mkdir(exist_ok=True)
                (target / "jobs").mkdir(exist_ok=True)
                write_config_if_missing(target)
                if name == "demo":
                    seed_demo(pack_root, target)
    return created


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--runtime", type=Path, required=True)
    parser.add_argument("--pipeline-dirs", default="")
    parser.add_argument("--seed-demo", action="store_true")
    args = parser.parse_args(argv)
    bootstrap_runtime(
        args.root,
        args.runtime,
        args.pipeline_dirs,
        seed_demo_project=args.seed_demo,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
